version: '3.5'

services:
  kurkkutraining:
     build: kurkkutraining
     build: ./ml-kurkkumopo-training-master
     volumes:
       - /tmp/model:/src/model
       - /tmp/imgs:/src/imgs
       - /tmp/data:/data


  kurkkubackend:
     image: kurkkubackend
     build: ./ml-kurkkumopo-backend-master
     volumes:
       - /tmp/model:/src/model
     ports:
       - 5000:5000
        
  kurkkufrontend:
     image: kurkkufrontend
     build: ./ml-kurkkumopo-frontend-master
     ports:
       - 3000:3000